# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


required = [
    # Pigeon is the command used to generate the Flux parser from the PEG description
    "github.com/mna/pigeon",
    # goreleaser is a utility to build and upload to S3
    "github.com/goreleaser/goreleaser",
    "github.com/gogo/protobuf/protoc-gen-gogofaster",
    "github.com/kevinburke/go-bindata"
]


[[constraint]]
  name = "github.com/goreleaser/goreleaser"
  version = "0.84.0"

[[constraint]]
  name = "github.com/kevinburke/go-bindata"
  version = "3.11.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  branch = "platform"

# Pigeon hasn't made official releases for a while, we need to use master for now.
# We plan to replace pigeon with a hand written parser, as such this dependency is short lived.
[[override]]
  branch = "master"
  name = "github.com/mna/pigeon"

# Dependency is pinned to explicit revision rather than latest release because
# latest release pre-dates context, which we need.
[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  revision = "d1898390779332322e6b5ca5011da4bf249bb056"

# Prometheus are currently pre v1.0, so the API is changing considerably.
# The latest release (0.8) predates exported API requirements.
[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "661e31bf844dfca9aeba15f27ea8aa0d485ad212"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/kevinburke/go-bindata"
    non-go = true
    unused-packages = false

[[constraint]]
  branch = "master"
  name = "github.com/andreyvit/diff"

[[constraint]]
  name = "github.com/google/go-github"
  branch = "master"

# We are using v2 branch because no releases have been made using v2.
[[constraint]]
  name = "gopkg.in/robfig/cron.v2"
  branch = "v2"

[[constraint]]
  branch = "feature/uint64-id"
  name = "github.com/influxdata/flux"
